"""
Builds and sends the NEPM daily summary email at 5:30pm Sydney time.
Queries Xero for today's automation-created invoices and credit notes.
"""
import logging
import re
from datetime import date
import pytz

import summary_theme as theme

logger = logging.getLogger(__name__)
SYDNEY = pytz.timezone('Australia/Sydney')


def _parse_job_name(description: str) -> str:
    """Extract job name from a Xero line item description."""
    m = re.match(r'^(?:Deposit|Final(?: Invoice)?|Credit)\s*[\u2013-]\s*(.+?)\s*[\u2013-]', description)
    return m.group(1).strip() if m else description[:50]


def _parse_type(reference: str) -> str:
    """Extract invoice type from reference e.g. CU-abc123-deposit → deposit"""
    parts = reference.split('-')
    return parts[-1] if parts else 'unknown'


def _dollars(amount) -> str:
    return f'${float(amount):,.2f}'


def build_summary(xero) -> dict:
    """Fetch today's documents from Xero and return structured summary data."""
    docs = xero.get_todays_documents()

    deposits = []
    finals   = []
    credits  = []

    for inv in docs['invoices']:
        ref      = inv.get('Reference', '')
        inv_type = _parse_type(ref)
        client   = inv.get('Contact', {}).get('Name', 'Unknown')
        subtotal = float(inv.get('SubTotal', 0))
        number   = inv.get('InvoiceNumber', '')
        desc     = inv.get('LineItems', [{}])[0].get('Description', '') if inv.get('LineItems') else ''
        job      = _parse_job_name(desc)

        row = {'client': client, 'job': job, 'amount': subtotal, 'number': number}
        if inv_type == 'deposit':
            deposits.append(row)
        else:
            finals.append(row)

    for cn in docs['credit_notes']:
        client   = cn.get('Contact', {}).get('Name', 'Unknown')
        subtotal = float(cn.get('SubTotal', 0))
        number   = cn.get('CreditNoteNumber', '')
        desc     = cn.get('LineItems', [{}])[0].get('Description', '') if cn.get('LineItems') else ''
        job      = _parse_job_name(desc)
        credits.append({'client': client, 'job': job, 'amount': subtotal, 'number': number})

    total_in    = sum(r['amount'] for r in deposits)
    total_out   = sum(r['amount'] for r in finals)
    total_cr    = sum(r['amount'] for r in credits)
    net_revenue = total_in + total_out - total_cr

    return {
        'deposits':    deposits,
        'finals':      finals,
        'credits':     credits,
        'total_in':    total_in,
        'total_out':   total_out,
        'total_cr':    total_cr,
        'net_revenue': net_revenue,
        'has_activity': bool(deposits or finals or credits),
    }


def _section(title, rows_data, accent):
    """A Xero-document section table with an ex/inc-GST subtotal line."""
    if not rows_data:
        return ''
    headers = [('JOB', 'left'), ('CLIENT', 'left'), ('AMOUNT (EX GST)', 'right'), ('REF', 'right')]
    table_rows = [
        [(r['job'], 'left'), (r['client'], 'left'), (theme.dollars(r['amount']), 'right'), (r['number'], 'right')]
        for r in rows_data
    ]
    section = theme.data_table(title, headers, table_rows, accent)
    sub = sum(r['amount'] for r in rows_data)
    subtotal = (
        f'<tr><td style="padding:4px 16px 8px;">'
        f'<div style="text-align:right;font-size:12px;color:{theme.INK_SOFT};font-family:{theme.BODY_FONT};padding:6px 0;">'
        f'Subtotal: <strong>{theme.dollars(sub)}</strong> ex GST &nbsp;|&nbsp; '
        f'<strong>{theme.dollars(sub * 1.1)}</strong> inc GST</div></td></tr>'
    )
    return section + subtotal


def build_html(summary: dict, today_str: str) -> str:
    """Build the branded HTML email body (NEPM monochrome + red)."""
    footer = 'Generated by NEPM Automation at 5:30pm Sydney time'
    subtitle = f'Daily Summary &mdash; {today_str}'

    if not summary['has_activity']:
        body = theme.empty_state(
            'No invoices or credit notes were created today.<br>'
            'The automation ran as expected &mdash; just a quiet one.'
        )
        return theme.page(subtitle, body, footer)

    # Category accents — monochrome + red: deposits=red, finals=ink, credits=muted
    c_dep, c_fin, c_cr = theme.RED, theme.INK, theme.MUTED

    cards = theme.cards_block([
        [
            theme.stat_card(len(summary['deposits']), 'New Jobs In', c_dep),
            theme.stat_card(len(summary['finals']), 'Jobs Completed', c_fin),
            theme.stat_card(len(summary['credits']), 'Credit Notes', c_cr),
        ],
        [
            theme.stat_card(theme.dollars(summary['total_in']), 'Deposit Value', c_dep),
            theme.stat_card(theme.dollars(summary['total_out']), 'Final Invoice Value', c_fin),
            theme.stat_card(theme.dollars(summary['net_revenue']), 'Net Revenue Today', c_fin),
        ],
    ])

    total = summary['total_in'] + summary['total_out'] + summary['total_cr']
    dep_pct = int(summary['total_in'] / total * 100) if total else 0
    fin_pct = int(summary['total_out'] / total * 100) if total else 0
    cr_pct = max(0, 100 - dep_pct - fin_pct)
    bar = theme.stacked_bar(
        [(dep_pct, c_dep, 'Deposits'), (fin_pct, c_fin, 'Finals'), (cr_pct, c_cr, 'Credits')],
        title='Revenue breakdown',
    )

    sections = (
        _section('Deposit Invoices &mdash; Jobs In', summary['deposits'], c_dep) +
        _section('Final Invoices &mdash; Jobs Out', summary['finals'], c_fin) +
        _section('Credit Notes', summary['credits'], c_cr)
    )

    return theme.page(subtitle, cards + bar + sections, footer)


def send_daily_summary(xero, gmail, recipients: list, sendgrid_api_key: str = '',
                       clickup_token: str = '', clickup_channel: str = ''):
    """Build and send the daily summary email via SendGrid."""
    from xero_client import XeroAuthError
    import notifier

    try:
        today_str = date.today().strftime('%A, %d %B %Y')
        summary   = build_summary(xero)
        html      = build_html(summary, today_str)

        activity = (
            f"{len(summary['deposits'])} deposit{'s' if len(summary['deposits'])!=1 else ''}, "
            f"{len(summary['finals'])} final{'s' if len(summary['finals'])!=1 else ''}"
            if summary['has_activity'] else 'No activity'
        )
        subject = f"NEPM Daily Summary \u2014 {today_str} \u2014 {activity}"

        gmail.send_email(
            to_list          = recipients,
            subject          = subject,
            body             = f"NEPM Daily Summary\n{today_str}\n{activity}",
            html_body        = html,
            sendgrid_api_key = sendgrid_api_key,
        )
        logger.info(f'Daily summary sent \u2192 {recipients} ({activity})')

    except XeroAuthError as e:
        logger.error(f'Daily summary failed — Xero auth error: {e}')
        notifier.xero_auth_failed(
            gmail, recipients,
            sendgrid_api_key=sendgrid_api_key,
            clickup_token=clickup_token,
            clickup_channel=clickup_channel,
        )

    except Exception as e:
        logger.error(f'Failed to send daily summary: {e}')
